### ISSUE TITLE
If used in a project with Crashlytics the error is not reported to crashlytics.

### ISSUE THREAD

**Issue by mattcarron** [Cookizz/RxJavaStackTracer#1]
Hi there :)

In our project we are using Crashlytics and your RxJavaStackTracer like this:
`RxJavaPlugins.getInstance().registerObservableExecutionHook(new RxJavaStackTracer());`

The issue is when RxJavaStackTracer in included, Crashlytics is not logging fatal crashes caused by Rx Observables e.g. not implementing onError. Have you seen this before or know why this could be happening?

Cheers,
Matt

**Comment by mattcarron** [comment]
I found a solution for my issue 👍 

In the onError override in the OperatorTraceOnError class's call method I have removed the use of TracedException and just add the trace to the original throwable. By maintaining the same reference Crashlytics gets the correct exception and posts it correctly.

from:
`child.onError(new TracedException(throwable, trace));`

to:
`throwable.setStackTrace(trace);`

Was there any reason why you were creating a new exception instance?

**Comment by Cookizz** [comment]
Sorry for having your issue too late.

The reason why I modify the given `Exception` rather than emitting a new `TracedException` is to **avoid type pollution to the outside exception handlings**.

For example, we may intercept an error from an http request and throw a `CustomizedIOException` according to error code:

``` java
if (statusCode / 100 != 2 && statusCode / 100 != 3) {
    throw new ApiException(statusCode,
        error.message,
        error.code,
        error.name);
}
```

Then we may use the exception instance in other places and deal with them:

``` java
new Action1<Throwable>() {
    @Override
    public void call(Throwable throwable) {
        if (throwable instanceof ApiException) {
            ErrorData data = new ErrorData();
            data.code = ((ApiException) throwable).getCode();
            data.message = throwable.getMessage();
            view.onError(data);
        }
    }
}
```

Apparantly, it'll cause ClassCastException in such case when mapping the original `Exception` to `TracedException`.

**Comment by Cookizz** [comment]
As for your first question, yes, RxJavaStackTracer will not show full stack trace in the case of missing `onError` implementations.

However, I think, we should never omit any `onError` when using RxJava for developing Android production, which is a bad practice, isn't it?
